
package com.workshop.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VariousServiceImpl", targetNamespace = "http://www.mjtoolbox.com/workshop", wsdlLocation = "http://localhost:8080/workshop_ws/VariousService?wsdl")
public class VariousServiceImpl
    extends Service
{

    private final static URL VARIOUSSERVICEIMPL_WSDL_LOCATION;
    private final static WebServiceException VARIOUSSERVICEIMPL_EXCEPTION;
    private final static QName VARIOUSSERVICEIMPL_QNAME = new QName("http://www.mjtoolbox.com/workshop", "VariousServiceImpl");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/workshop_ws/VariousService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VARIOUSSERVICEIMPL_WSDL_LOCATION = url;
        VARIOUSSERVICEIMPL_EXCEPTION = e;
    }

    public VariousServiceImpl() {
        super(__getWsdlLocation(), VARIOUSSERVICEIMPL_QNAME);
    }

    public VariousServiceImpl(WebServiceFeature... features) {
        super(__getWsdlLocation(), VARIOUSSERVICEIMPL_QNAME, features);
    }

    public VariousServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, VARIOUSSERVICEIMPL_QNAME);
    }

    public VariousServiceImpl(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VARIOUSSERVICEIMPL_QNAME, features);
    }

    public VariousServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VariousServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VariousService
     */
    @WebEndpoint(name = "VariousServicePort")
    public VariousService getVariousServicePort() {
        return super.getPort(new QName("http://www.mjtoolbox.com/workshop", "VariousServicePort"), VariousService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VariousService
     */
    @WebEndpoint(name = "VariousServicePort")
    public VariousService getVariousServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.mjtoolbox.com/workshop", "VariousServicePort"), VariousService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VARIOUSSERVICEIMPL_EXCEPTION!= null) {
            throw VARIOUSSERVICEIMPL_EXCEPTION;
        }
        return VARIOUSSERVICEIMPL_WSDL_LOCATION;
    }

}
